FROM bitnami/fluentd:1.12.3
LABEL maintainer "JFrog <partner-support@jfrog.com>"

## Fix the file permission of root on fluentd directory
USER root
RUN chown -R 1001:1001 /opt/bitnami/fluentd
## Reset back to user
USER 1001
## Installing required JFrog fluentd plugins
RUN fluent-gem install fluent-plugin-splunk-enterprise
RUN fluent-gem install fluent-plugin-datadog
RUN fluent-gem install fluent-plugin-elasticsearch
RUN fluent-gem install fluent-plugin-jfrog-siem

