resources:
  - name: source_repo
    type: GitRepo
    configuration:
      gitProvider: github_integration
      path: jfrog/log-analytics
      branches:
        include: harrison_pipelines


pipelines:
  - name: siem_plugin_test
    steps:
      - name: siem_plugin_test_step
        type: Bash
        configuration:
          inputResources:
            - name: source_repo
              trigger: true
          runtime:
            type: image
            image:
              custom:
                name: ruby
                tag: '3.0.2'
                autoPull: true
        execution:
          onExecute:
            - cd $res_source_repo_resourcePath/fluentd/plugins/input/fluentd-plugin-jfrog-siem
            - ls
            - bundle --version
            - bundle install
            - rspec
