{
 "title": "JFrog Platform Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests by Artifact",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (artifact) (jfrog_rt_req{artifact!=\"\"}))",
     "legendFormat": "{{artifact}}"
    }
   ]
  },
  {
   "title": "Requests by Repo",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (repo) (jfrog_rt_req{repo!=\"\"}) )",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Download Data Transfers (GBs) Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decgbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(jfrog_rt_data_download)/1000000000"
    }
   ]
  },
  {
   "title": "Upload Data Transfers (GBs) Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jfrog_rt_data_upload)/1000000000"
    }
   ]
  },
  {
   "title": "Artifactory 5xx Status Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jfrog_rt_req{return_status=~\"5.*\"}"
    }
   ]
  },
  {
   "title": "Artifactory Errors Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jfrog_rt_log_level{log_level=\"ERROR\"}"
    }
   ]
  },
  {
   "title": "Xray 5xx Status Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jfrog_xray_req{return_status=~\"5.*\"}"
    }
   ]
  },
  {
   "title": "Artifactory 4xx Status Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jfrog_rt_req{return_status=~\"4.*\"}"
    }
   ]
  },
  {
   "title": "Xray Errors Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jfrog_xray_log_level{log_level=\"ERROR\"}"
    }
   ]
  },
  {
   "title": "Artifactory User Access",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (jfrog_rt_access_by_user))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Active Downloading IPs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_address) (jfrog_rt_data_download))"
    }
   ]
  },
  {
   "title": "Active Uploading IPs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_address) (jfrog_rt_data_upload))"
    }
   ]
  }
 ]
}