FROM bitnami/fluentd:latest
LABEL maintainer "JFrog <partner-support@jfrog.com>"

## Fix the file permission of root on fluentd directory
USER root
##Env variables
ENV JF_PRODUCT_DATA_INTERNAL=JF_PRODUCT_DATA_INTERNAL_VALUE

COPY fluent.conf.rt /opt/bitnami/fluentd/conf/fluentd.conf
RUN mkdir -p "$JF_PRODUCT_DATA_INTERNAL"
RUN chown -R 1001:1001 /opt/bitnami/fluentd/
## Reset back to user
USER 1001
## Required JFrog fluentd plugins

