require "bundler"
Bundler::GemHelper.install_tasks

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs.push("lib", "test", 'lib/fluent/plugin')
  t.test_files = FileList["test/**/test_*.rb"]
  t.verbose = true
  t.warning = false
end

task default: [:test]
